# Generated by Django 3.0.3 on 2020-03-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0002_cometario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cometario',
            name='data_publicacao',
            field=models.DateField(blank=True, max_length=128, null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AddField(
            model_name='cometario',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cometario',
            name='comentarios',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='título'),
        ),
    ]
