# Generated by Django 3.0.3 on 2020-03-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_noticias', '0003_auto_20200306_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cometario',
            name='comentarios',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Comentário'),
        ),
    ]
